# RBAC (Role-Based Access Control) uses four core resources:

# Namespace-scoped: Role + RoleBinding (applies only inside a specific namespace)

# Cluster-wide: ClusterRole + ClusterRoleBinding (applies across all namespaces and to non-namespaced resources like Nodes or PVs)


apiVersion: rbac.authorization.k8s.io/v1
kind: Role   # creating one admin role for assign group
metadata:
  namespace: roboshop
  name: devops-tls # roboshop pod-admin

rules:  # this are the permissions for the role 
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]  # which resources
  verbs: ["*"]  # what are the actions

  # ["*"] ---> * means full CURD access

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: devops-tls
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]


  # You could write resources: ["*"] in the ClusterRole, but that would grant full cluster-admin control over the entire Kubernetes 
  # infrastructure (including all other namespaces, nodes, certificates, and cluster settings).

 # Listing only nodes, persistentvolumes, and storageclasses with verbs: ["get", "list", "watch"] ensures the team gets read-only visibility
 # into underlying infrastructure without giving them full cluster-wide superuser power.