# RBAC (Role-Based Access Control) uses four core resources:

# Namespace-scoped: Role + RoleBinding (applies only inside a specific namespace)

# Cluster-wide: ClusterRole + ClusterRoleBinding (applies across all namespaces and to non-namespaced resources like Nodes or PVs)


apiVersion: rbac.authorization.k8s.io/v1
kind: Role   # creating one admin role for assign group
metadata:
  namespace: roboshop
  name: devops-tls # roboshop pod-admin

rules:  # this are the permissions for the role 
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]  # which resources
  verbs: ["*"]  # what are the actions

  # ["*"] ---> * means full CURD access