apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-tls
  namespace: roboshop

subjects: # subjects (WHO): The user, group, or service account receiving access (in your case, the role devops-trainees giving to group).
# Can bind to a ServiceAccount, User, or Group
- kind: Group # creating group for devops-tls
  name: devops-tls # group name
  namespace: roboshop
  apiGroup: rbac.authorization.k8s.io

roleRef: # Role Reference is the field that specifies which set of permissions (Role or ClusterRole) you are actually granting to the subjects.
  kind: Role
  name: devops-tls
  apiGroup: rbac.authorization.k8s.io

# Role = The permission list (Rules).

# subjects = The target user, group, or service account (Who).

# roleRef = The pointer that tells Kubernetes: "Take the permissions defined inside this specific Role and apply them to the subjects above."