# POD want to get passwords by accessing Secrets Manager. create k8 service-account for pod . associate service account to IAM role. 
# in IAM role set up read only permission Policy to get passwords from Secrets Manager

# pod to check other pods and services that are running we use service-account

# k8 want to get resources from outside then we use annotations

apiVersion: v1
kind: Pod
metadata:
  name: aws-cli # pod name
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    purpose: poc
spec:
  serviceAccountName: roboshop-secret-reader # field attaches a specific Kubernetes ServiceAccount to the Pod to give it AWS permissions via IRSA (IAM Roles for Service Accounts).
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "1000"] # You only need command for containers like utility/CLI tools that don't run continuous background services.

    